---
title: "**Field Technician Position**"
output:
  html_document: default
  pdf_document: default
---

<style type="text/css">
h1.title {
  font-size: 31px;
  text-align: left;
  color:black;
}
</style>





### **Work Description**

This one-year position (start and end date are somewhat flexible) will involve co-leading monthly field expeditions for [Ekipa Fanihy](team.html). The new Field Technician will spend approximately 70% of time in the field, in part with Ekipa Fanihy's monthly missions to roost sites for *Pteropus rufus,* *Eidolon dupreanum,* and *Rousettus madagascariensis* in the District of Moramanga, Madagascar. 

The team will travel up to a full day's journey for each mission in a vehicle with hired driver sponsored by [Institut Pasteur de Madagascar ](http://www.pasteur.mg/) (IPM). In the field, the team will reside in tents provided by the project for up to two weeks at a time. During field missions, a local cook will be hired to prepare meals, and all expenses (including food) will be funded by the project.

While in the field, the tech will join the rest of the field team to capture bats, collect biological samples (blood, urine, feces, saliva, ectoparasites, wing punches, tooth extractions from a subset of bats under isofluorane anesthesia), and undertake basic sample preparation (i.e. centrifugation) and sample storage in liquid nitrogen. 

In between field missions (30% of the time), the tech will live in a shared house with the other foreign team members in Madagascar's capitol city of Antananarivo (housing includes a modern kitchen, ample living space, modern bathroom, WiFi, on-site security, and weekly cleaning services). In Antananarivo ('Tana'), the new tech will work with Ekipa Fanihy to further treat and organize samples on the laboratory campus of IPM. Together, all techs will be additionally responsible for restocking, packing, and preparation of field supplies for recurring field missions. Techs may be asked to participate in basic laboratory manipulations of samples (DNA/RNA extractions, PCR, etc.) at IPM after field obligations have been fulfilled.

See [Research](research_interests.html) for an overview of the scientific questions underpinning the field work, and visit our [blog](www.brooklab.org/blog/) to track our team's progress in the field.

---

### **Qualifications**

We are open to candidates from all backgrounds, but an ideal candidate will possess some combination of the following background traits or experiences:

* a Bachelor of Science degree or equivalent in biology, ecology, wildlife conservation, or a related field
* past field experience involving handling of mammals
* prior camping experience
* prior experience living and/or travelling in the developing world

Bonus traits include:

* prior experience working with bats, specifically, or fruit bats in particular
* prior field experience drawing blood from mammals
* prior field experience extracting teeth from mammals
* prior field experience maintaining anesthesic regimens for wild-caught mammals
* an academic interest in disease ecology
* interest in science communication, outreach, or writing
* French and/or Malagasy language skills

Candidates who do not meet the above requirements will not be automatically discarded but will need to justify their interest in this position and commitment to catching up on the necessary skills in their application. Please do not hesitate to reach out to Cara Brook at [cbrook@uchicago.edu](cbrook@uchicago.edu) with any questions or concerns.

---

### **Another note on diversity and inclusion**

**We are an equal-opportunity group. Applicants from underrepresented backgrounds, ethnicities, genders, sexual orientations, and lifestyles are enthusiastically encouraged to apply.** We acknowledge that we are unable to provide a salary competitive with full-time US-based employment for Field Project Managers at this time. However, we are committed to ensuring that this opportunity does not fall under the "unpaid internship" designation, which has been shown to reinforce socioeconomic inequities. Therefore, if the above compensation description is inadequate for your needs, please inform us of this in your application submission. We will review applications on a case-by-case basis and do our best to making this opportunity accessible for the right applicant, independent of financial constraints.
