---
title: "**Publications**"
output:
  html_document: default
  pdf_document: default
---

<style type="text/css">
h1.title {
  font-size: 31px;
  text-align: left;
  color:black;
}
</style>

<br>
<div style="text-align: left; font-size: 1.4em;">
<a href="https://scholar.google.com/citations?user=jDzdfmMAAAAJ&hl=en&oi=ao">Google Scholar Page</a></div>

<br>

<div style="text-align: left; font-size: 1.4em;">
**In Review**
</div>

- Albery GF, Becker DJ, Brierley L, **Brook CE**, Christofferson RC, Cohen LE, Dallas TA, Eskew EA, Fagre A, Farrell M, Glennon E, Guth S, Joseph MB, Mollentze N, Neely BA, Poisot T, Rasmussen AL, Ryan SJ, Sjodin AR, Seifert S, Sorrell EM, and Carlson CJ. In Review. Modeling cross-species viral transmission and predicting zoonotic potential. *Nature Microbiology.*


- Annapragada A, **Brook CE**, Luskin MS, Rahariniaina RP, Helin M, Razafinarivo O, Ralaiarison AR, Randriamady HJ, Olson LE, Goodman SM, Golden CD. In Review. Evaluation of tenrec population viability and potential sustainable management under hunting pressure in northeastern Madagascar. *Biodiversity and Conservation.*

<div style="text-align: left; font-size: 1.4em;">
**In Revision**
</div>

- Ravelomanantsoa NAF, Guth S, Andrianiaina A, Andry S, Gentles A, Ranaivoson HC, and **Brook CE**. In Revision. The zoonotic potential of bat-borne coronaviruses. *Emerging Topics in Life Sciences.*

<div style="text-align: left; font-size: 1.4em;">
**In Press**
</div>

- Gentles A, Guth S, Rozins C, and **Brook CE**. In Press. A review of mechanistic models of viral dynamics in bat reservoirs for zoonotic disease. *Pathogens and Global Health.* 

<div style="text-align: left; font-size: 1.4em;">
**2020**
</div>

- Rocha R, Aziz SA, **Brook CE**, Carvalho WD, Cooper-Bohannon R, Frick WF, Huang JCC, Kingston T, Lopez-Baucells A, Maas B, Mathews F, Medellin RA, Olival KJ, Peel AJ, Plowright RK, Razgour O, Rebelo H, Rodrigues L, Rossiter SJ, Russo D, Straka TM, Teeling EC, Treuer T, Voigt CC, and  Webala PW. Bat conservation and zoonotic disease risk: A research agenda to prevent misguided persecution in the aftermath of COVID-19. 2020. *Animal Conservation.* doi: [10.1111/acv.12636](https://doi.org/10.1111/acv.12636).

- Olival KJ\*, Cryan PM\*, Amman BR, Baric RS, Blehert DS, **Brook CE**, Calisher CH, Castle KT, Coleman JTH, Daszak P, Epstein JH, Field H, Frick WF, Gilbert AT, Hayman DTS, Ip HS, Karesh WB, Johnson CK, Kading RK, Kingston T, Lorch JM, Mendendall IH, Peel AJ, Phelps KL, Plowright RK, Reeder DM, Reichard JD, Sleeman JM, Streicker DG, Towner JS, and Wang L-F. 2020. Possible risks of SARS-CoV-2 spillover to free-ranging wildlife: a case study of bats. 2020. *PLoS Pathogens.* 16(9): e1008758. doi: [10.1371/journal.ppat.1008758](https://doi.org/10.1371/journal.ppat.1008758).  \*=equal lead contributions

- Amen AM, Barry KW, Boyle JM, **Brook CE**, Choo S, Cornmesser LT, Dilworth DJ, Doudna JA\*, Ehrenberg AJ, Fedrigo I, Friedline SE, Graham TGW, Green R, Hamilton JR, Hirsh A, Hochstrasser ML, Hockemeyer D\*, Krishnappa N, Lari A, Li H, Lin-Shiao E, Lu T, Lyons EF, Mark KG, Martell LA, Martins ARO, McDevitt SL, Mitchell PS, Moehle EA, Naca CL, Nandakumar D, O’Brien E, Pappas DJ, Pestal K, Quach DL, Rubin BE, Sachdeva R, Stahl EC, Syed AM, Tan I-L, Tollner AL, Tsuchida CA, Tsui CK, Turkalo TK, Urnov F\*, Warf MB, Whitney ON, Witkowsky LB. 2020. Blueprint for a Pop-up SARS-CoV-2 Testing Lab. *Nature Biotechnology.* 38(7):791-797. doi: [10.1038/s41587-020-0583-3](https://doi.org/10.1038/s41587-020-0583-3). \*=equal senior contributions	

-	**Brook CE**, Boots M, Chandran KC, Dobson AP, Drosten C, Graham AL, Grenfell BT, Müller MA, Ng M, Wang LF, and van Leeuwen A. 2020. Accelerated viral dynamics in bat cell lines, with implications for zoonotic emergence. *eLife.* doi: [10.7554/eLife.48401](https://elifesciences.org/articles/48401).
    - Highlighted in [CNN special](https://cnnpressroom.blogs.cnn.com/2020/06/09/cnn-to-air-special-on-the-connection-between-bats-and-covid-19/): 'Bats: The Mystery Behind COVID-19' 
    - Profiled in the National Science Foundation's '[4 Awesome Discoveries](https://www.youtube.com/watch?v=y5_g_pjf0eE&feature=youtu.be)' video series 
    - Covered in [The Economist](https://www.economist.com/science-and-technology/2020/04/18/bats-spread-viruses), [Science News](https://www.sciencenews.org/article/bats-immune-system-viruses-ebola-marburg-people), [Berkeley News](https://news.berkeley.edu/2020/02/10/coronavirus-outbreak-raises-question-why-are-bat-viruses-so-deadly/), the [Daily Cal](https://www.sciencenews.org/article/bats-immune-system-viruses-ebola-marburg-people)

<div style="text-align: left; font-size: 1.4em;">
**2019**
</div>

-	**Brook CE**. 2019. A batty concept goes viral. *Nature Ecology & Evolution.* 3(12): 1620-1621. doi: [10.1038/s41559-019-1045-5](https://www.nature.com/articles/s41559-019-1045-5).

- Guth S, Visher E, Boots M, and **Brook CE.** 2019. Host phylogenetic distance drives trends in virus virulence and transmissibility across the animal-human interface. *Philosophical Transactions of the Royal Society.* 374(1782): 20190296. doi: [10.1098/rstb.2019.0296](https://doi.org/10.1098/rstb.2019.0296).

- **Brook CE**, Ranaivoson HC, Broder CC, Cunningham AA, Héraud JM, Peel AJ, Gibson L, Wood JLN, Metcalf CJE\*, and Dobson AP\*. 2019. Disentangling serology to elucidate henipa- and filovirus transmission in Madagascar fruit bats. *Journal of Animal Ecology.* doi: [10.1111/1365-2656.12985](https://doi.org/10.1111/1365-2656.12985). \*=equal senior contributions. *Profiled in JAE blog [here](https://animalecologyinfocus.com/2019/04/16/disentangling-disease-transmission-in-madagascar-fruit-bats/).*

- **Brook CE**, Ranaivoson HC, Andriafidison D, Ralisata M, Razafimanahaka J, Héraud JM, Dobson AP, and Metcalf CJE. 2019. Population trends for two Malagasy fruit bats. *Biological Conservation.* 234: 165-171. doi: [10.1016/j.biocon.2019.03.032](https://doi.org/10.1016/j.biocon.2019.03.032).

-	Ranaivoson HC, Héraud JM, Goethert HK, Telford SR, Rabetafika L\* and **Brook CE**\*. Babesial infection in the Madagascan flying fox, *Pteropus rufus* É. Geoffroy, 1803. 2019. *Parasites & Vectors.* 12(51): 1307101933. doi:  [10.1186/s13071-019-3300-7](https://doi.org/10.1186/s13071-019-3300-7). \*=equal senior contributions

<div style="text-align: left; font-size: 1.4em;">
**2018**
</div>

- **Brook CE**, Herrera JP, Borgerson C, Fuller E, Andriamahazoarivosoa P, Rasolofoniaina BJR, Randrianasolo JLRR, Rakotondrafarasata ZRE, Randriamady HJ, Dobson AP, and Golden CD. 2018. Population viability and harvest sustainability for Madagascar lemurs. *Conservation Biology.* doi: [10.1111/cobi.13151](https://doi.org/10.1111/cobi.13151).

<div style="text-align: left; font-size: 1.4em;">
**2017**
</div>

- **Brook CE**, Bai Y, Yu EO, Ranaivoson HC, Shin H, Dobson AP, Metcalf CJE\*, Kosoy MY\* and Dittmar K\*. 2017. Elucidating transmission dynamics and host-parasite-vector relationships for rodent-borne *Bartonella* spp. in Madagascar. *Epidemics.* 20:56-66. \*= equal senior contributions doi: [10.1016/j.epidem.2017.03.004](https://doi.org/10.1016/j.epidem.2017.03.004).

<div style="text-align: left; font-size: 1.4em;">
**2016**
</div>

- Wesolowski A\*, Mensah K\*, **Brook CE**\*, Andrianjafimasy M, Winter A, Buckee CO, Razafindratsimendresy R, Tatem AJ, Heraud J-M\*\*, and Metcalf CJE. 2016\*\*. Introduction of Rubella-Containing-Vaccine to Madagascar: Implications for roll-out and local elimination across low-income countries. *Journal of the Royal Society Interface.* 13(177): 20151101. \* =  equal lead contributions; \*\*=equal senior contributions. doi: [10.1098/rsif.2015.110](https://doi.org/10.1098/rsif.2015.110).

<div style="text-align: left; font-size: 1.4em;">
**2015**
</div>

- **Brook CE**, Beauclair R, Ngwenya O, Worden L,  Ndeffo-Mbah M, Lietman TM, Satpathy SK,  Galvani AP, and Porco TP. 2015. Spatial heterogeneity in projected leprosy trends in India. *Parasites & Vectors.* 8(542): 2-11. doi: [10.1186/s13071-015-1124-7](https://doi.org/10.1186/s13071-015-1124-7).

- Rist CL, Ngonghala CN,  Garchitorena A, **Brook CE**, Ramananjato, Miller RC, Randrianarivelojosia M, Wright PC, Gillespie TR, and Bonds MH. 2015. Modeling the burden of poultry disease on the rural poor in Madagascar. *One Health.* doi: [10.1016/j.onehlt.2015.10.002](https://doi.org/10.1016/j.onehlt.2015.10.002).

- **Brook CE**, Bai Y, Dobson AP, Osikowicz L, Ranaivoson HC, Zhu Q, Kosoy MY, and Dittmar K. 2015. *Bartonella* spp. in fruit bats and blood-feeding ectoparasites in Madagascar. *PLoS Neglected Tropical Diseases.* 10 (2):e0003532. doi: [10.1371/journal.pntd.0003532](https://doi.org/10.1371/journal.pntd.0003532).

- **Brook CE** and Dobson AP. 2015. Bats as ‘special’ reservoirs for emerging zoonotic pathogens. *Trends in Microbiology.* doi: [10.1016/j.tim.2014.12.004](https://doi.org/10.1016/j.tim.2014.12.004).

- Guyton J and **Brook CE**. 2015. African Bats: Conservation in the Time of Ebola. *Therya.* 6(1): 69-88. doi: [10.12933/therya-15-244](https://doi.org/10.12933/therya-15-244).

- Young HS, McCauley DJ, Dirzo R, Goheen JR, Agwanda B, **Brook CE**, Castillo EO, Ferguson AW, Nyaga SN, McDonough MM, Palmer TM, Pringle RM, Young TP, and Helgen KM. 2015. Context dependence of land-use change on small mammal communities. *Ecological Applications.* (25):348–60. doi: [10.1890/14-0995.1](https://doi.org/10.1890/14-0995.1).

<div style="text-align: left; font-size: 1.4em;">
**2013**
</div>

- **Brook CE**, Bernstein DP, and Hadly EA. 2013. Human food subsidies and Common Raven occurrence in Yosemite National Park, CA. *Western Birds.* 44(2):127-34.
